# Generated by Django 3.2.5 on 2021-08-04 01:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontosDeColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=50)),
                ('materialColeta', models.CharField(max_length=50)),
                ('tipoMaterial', models.CharField(max_length=50)),               
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
